# Generated by Django 3.1.7 on 2021-04-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'permissions': [('alter_course', 'Can alter course'), ('create_course', 'Can create course'), ('delete_course', 'Can delete course'), ('manage', 'Can manage user')]},
        ),
    ]
