# Generated by Django 3.1.7 on 2021-04-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210410_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'permissions': [('alter_courses', 'Can alter course')]},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'permissions': [('alter_courses', 'Can alter course'), ('create_courses', 'Can create course'), ('delete_courses', 'Can delete course'), ('manage_users', 'Can manage user')]},
        ),
    ]
