# Generated by Django 3.1.7 on 2021-04-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'permissions': [('alter_courses', 'Can alter course'), ('create_exercise', 'Can create exercises')]},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'permissions': [('alter_courses', 'Can alter course'), ('create_courses', 'Can create course'), ('delete_courses', 'Can delete course'), ('manage_users', 'Can manage user'), ('create_exercise', 'Can create exercises')]},
        ),
    ]
