# Generated by Django 3.1.9 on 2021-05-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210505_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Manages Users')]},
        ),
    ]
