# Generated by Django 3.1.7 on 2021-04-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0002_auto_20210407_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='users.Student'),
        ),
    ]
