# Generated by Django 3.1.7 on 2021-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileexchange', '0005_auto_20210427_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='from_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
